FROM mcr.microsoft.com/dotnet/aspnet:10.0

RUN apt-get update && apt-get install -y git

RUN git clone -b backendMain https://github.com/MandichRiccardoITS/AtelierDoisneau.git fullBranch

RUN chmod +x /fullBranch/compiled/projectWork

ENTRYPOINT ["/fullBranch/compiled/projectWork"]