FROM mcr.microsoft.com/dotnet/aspnet:10.0

RUN apk update && apk add git && git clone -b backendMain https://github.com/MandichRiccardoITS/AtelierDoisneau.git fullBranch

WORKDIR /fullBranch/sorgente

ENTRYPOINT ["./projectWork"]