FROM nginx:alpine3.23

COPY nginx.conf /etc/nginx/nginx.conf

COPY ./frontend /frontend

RUN apt update && apt-get install openssl
RUN mkdir cert
RUN openssl req -x509 -newkey rsa:4096 -keyout cert/priv.key -out cert/cert.crt -sha256 -days 365 -nodes

RUN chown -R nginx:nginx /frontend

RUN mkdir /cert

COPY ./cert /cert

CMD ["nginx", "-g", "daemon off;"]